2021-02-23 12:58:10,962 INFO    MainThread:3281 [wandb_setup.py:_flush():70] setting env: {}
2021-02-23 12:58:10,962 INFO    MainThread:3281 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-02-23 12:58:10,962 INFO    MainThread:3281 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-23 12:58:10,962 INFO    MainThread:3281 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f469979e700>
2021-02-23 12:58:10,962 INFO    MainThread:3281 [wandb_init.py:_log_setup():319] Logging user logs to /home/johannbs/Desktop/IceCube_GNN/wandb/run-20210223_125810-revkw8vf/logs/debug.log
2021-02-23 12:58:10,962 INFO    MainThread:3281 [wandb_init.py:_log_setup():320] Logging internal logs to /home/johannbs/Desktop/IceCube_GNN/wandb/run-20210223_125810-revkw8vf/logs/debug-internal.log
2021-02-23 12:58:10,962 INFO    MainThread:3281 [wandb_init.py:init():351] calling init triggers
2021-02-23 12:58:10,962 INFO    MainThread:3281 [wandb_init.py:init():356] wandb.init called with sweep_config: {}
config: {}
2021-02-23 12:58:10,962 INFO    MainThread:3281 [wandb_init.py:init():371] re-initializing run, found existing run on stack: 3j4le1u9
2021-02-23 12:58:10,963 INFO    MainThread:3281 [wandb_run.py:finish():1068] finishing run johannbs/stopped_muons/3j4le1u9
2021-02-23 12:58:10,963 INFO    MainThread:3281 [wandb_init.py:_jupyter_teardown():250] cleaning up jupyter logic
2021-02-23 12:58:10,963 INFO    MainThread:3281 [jupyter.py:save_history():208] not saving jupyter history
2021-02-23 12:58:10,963 INFO    MainThread:3281 [wandb_run.py:_atexit_cleanup():1381] got exitcode: 0
2021-02-23 12:58:10,963 INFO    MainThread:3281 [wandb_run.py:_restore():1353] restore
2021-02-23 12:58:11,149 INFO    MainThread:3281 [wandb_run.py:_wait_for_finish():1504] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 812
  total_bytes: 812
}

