2021-02-23 12:18:12,977 INFO    MainThread:32126 [wandb_setup.py:_flush():70] setting env: {}
2021-02-23 12:18:12,977 INFO    MainThread:32126 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-02-23 12:18:12,977 INFO    MainThread:32126 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-23 12:18:12,977 INFO    MainThread:32126 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd3b8522d60>
2021-02-23 12:18:12,977 INFO    MainThread:32126 [wandb_init.py:_log_setup():319] Logging user logs to /home/johannbs/Desktop/IceCube_GNN/wandb/run-20210223_121812-fa55gpga/logs/debug.log
2021-02-23 12:18:12,978 INFO    MainThread:32126 [wandb_init.py:_log_setup():320] Logging internal logs to /home/johannbs/Desktop/IceCube_GNN/wandb/run-20210223_121812-fa55gpga/logs/debug-internal.log
2021-02-23 12:18:12,978 INFO    MainThread:32126 [wandb_init.py:init():351] calling init triggers
2021-02-23 12:18:12,978 INFO    MainThread:32126 [wandb_init.py:init():356] wandb.init called with sweep_config: {}
config: {}
2021-02-23 12:18:12,978 INFO    MainThread:32126 [wandb_init.py:init():404] starting backend
2021-02-23 12:18:12,989 INFO    MainThread:32126 [backend.py:ensure_launched():81] starting backend process...
2021-02-23 12:18:12,997 INFO    MainThread:32126 [backend.py:ensure_launched():85] started backend process with pid: 32162
2021-02-23 12:18:12,999 INFO    MainThread:32126 [wandb_init.py:init():413] backend started and connected
2021-02-23 12:18:13,000 INFO    MainThread:32126 [wandb_init.py:init():436] updated telemetry
2021-02-23 12:18:13,001 INFO    MainThread:32126 [wandb_init.py:init():459] communicating current version
2021-02-23 12:18:13,749 INFO    MainThread:32126 [wandb_init.py:init():464] got version response upgrade_message: "wandb version 0.10.20 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-02-23 12:18:13,749 INFO    MainThread:32126 [wandb_init.py:init():472] communicating run to backend with 30 second timeout
2021-02-23 12:18:13,966 INFO    MainThread:32126 [wandb_init.py:init():495] starting run threads in backend
2021-02-23 12:18:15,483 INFO    MainThread:32126 [wandb_run.py:_console_start():1411] atexit reg
2021-02-23 12:18:15,483 INFO    MainThread:32126 [wandb_run.py:_redirect():1274] redirect: SettingsConsole.WRAP
2021-02-23 12:18:15,483 INFO    MainThread:32126 [wandb_run.py:_redirect():1309] Wrapping output streams.
2021-02-23 12:18:15,484 INFO    MainThread:32126 [wandb_run.py:_redirect():1325] Redirects installed.
2021-02-23 12:18:15,484 INFO    MainThread:32126 [wandb_init.py:init():518] run started, returning control to user process
2021-02-23 12:18:15,484 INFO    MainThread:32126 [wandb_config.py:__setitem__():142] config set hidden_states = 64 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fd380d5cd30>>
2021-02-23 12:18:15,484 INFO    MainThread:32126 [wandb_run.py:_config_callback():663] config_cb hidden_states 64 None
2021-02-23 12:18:15,484 INFO    MainThread:32126 [wandb_config.py:__setitem__():142] config set forward = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fd380d5cd30>>
2021-02-23 12:18:15,484 INFO    MainThread:32126 [wandb_run.py:_config_callback():663] config_cb forward False None
2021-02-23 12:18:15,484 INFO    MainThread:32126 [wandb_config.py:__setitem__():142] config set dropout = 0.3 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fd380d5cd30>>
2021-02-23 12:18:15,484 INFO    MainThread:32126 [wandb_run.py:_config_callback():663] config_cb dropout 0.3 None
2021-02-23 12:18:15,485 INFO    MainThread:32126 [wandb_config.py:__setitem__():142] config set learning_rate = 0.0005 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fd380d5cd30>>
2021-02-23 12:18:15,485 INFO    MainThread:32126 [wandb_run.py:_config_callback():663] config_cb learning_rate 0.0005 None
2021-02-23 12:18:15,485 INFO    MainThread:32126 [wandb_config.py:__setitem__():142] config set batch_size = 512 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fd380d5cd30>>
2021-02-23 12:18:15,485 INFO    MainThread:32126 [wandb_run.py:_config_callback():663] config_cb batch_size 512 None
2021-02-23 12:18:15,485 INFO    MainThread:32126 [wandb_config.py:__setitem__():142] config set loss_func = loss_func_linear_angle - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fd380d5cd30>>
2021-02-23 12:18:15,485 INFO    MainThread:32126 [wandb_run.py:_config_callback():663] config_cb loss_func loss_func_linear_angle None
2021-02-23 12:18:15,486 INFO    MainThread:32126 [wandb_config.py:__setitem__():142] config set n_neighbors = 6 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fd380d5cd30>>
2021-02-23 12:18:15,486 INFO    MainThread:32126 [wandb_run.py:_config_callback():663] config_cb n_neighbors 6 None
2021-02-23 12:49:26,794 INFO    MainThread:32126 [wandb_init.py:_pause_backend():240] pausing backend
2021-02-23 12:49:26,996 INFO    MainThread:32126 [wandb_run.py:_atexit_cleanup():1381] got exitcode: 0
2021-02-23 12:49:26,996 INFO    MainThread:32126 [wandb_run.py:_restore():1353] restore
2021-02-23 12:49:26,996 INFO    MainThread:32126 [wandb_run.py:_restore():1353] restore
2021-02-23 12:49:32,565 ERROR   MainThread:32126 [wandb_run.py:_atexit_cleanup():1399] Problem finishing run
Traceback (most recent call last):
  File "/home/johannbs/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1389, in _atexit_cleanup
    self._on_finish()
  File "/home/johannbs/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1547, in _on_finish
    self._backend.interface.publish_telemetry(self._telemetry_obj)
  File "/home/johannbs/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 225, in publish_telemetry
    self._publish(rec)
  File "/home/johannbs/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 511, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
